name: Deploy

on:
  push:
    branches:
      - master
      - development
      - feat/githubActions

jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    strategy:
      matrix:
        node-version: [16.x]
    
    env:
      API_VERSION: ${{ secrets.STORYBOOK_TOKEN }}
      INITIAL_ROUTE: ${{ secrets.INITIAL_ROUTE }}
      IP_SERVER: ${{ secrets.IP_SERVER }}
      PORT: ${{ secrets.PORT }}
      
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        
